# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "theme-app-extension"
client_id = "dc5239040fe3de581a220c9c9d51c0c7"
application_url = "https://translated-fourth-calculate-outlet.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://translated-fourth-calculate-outlet.trycloudflare.com/auth/callback",
  "https://translated-fourth-calculate-outlet.trycloudflare.com/auth/shopify/callback",
  "https://translated-fourth-calculate-outlet.trycloudflare.com/api/auth/callback",
  "https://translated-fourth-calculate-outlet.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-si-li-withdata.myshopify.com"
